### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [nazar220160/TGConvertor#8]
from TGConvertor.manager.manager import SessionManager

Traceback (most recent call last):
  File "D:\MyProjects\project\app.py", line 7, in <module>
    from BotCore.handlers.main_router import router
  File "D:\MyProjects\project\BotCore\handlers\__init__.py", line 1, in <module>
    from . import (
  File "D:\MyProjects\project\BotCore\handlers\accoutns\__init__.py", line 1, in <module>
    from . import (
  File "D:\MyProjects\project\BotCore\handlers\accoutns\AccountsAddForm.py", line 5, in <module>
    from TGConvertor.manager.manager import SessionManager
  File "D:\MyProjects\project\venv\lib\site-packages\TGConvertor\__init__.py", line 8, in <module>
    from .manager import manager
  File "D:\MyProjects\project\venv\lib\site-packages\TGConvertor\manager\manager.py", line 6, in <module>
    from .sessions.pyro import PyroSession
  File "D:\MyProjects\project\venv\lib\site-packages\TGConvertor\manager\sessions\pyro.py", line 53, in <module>
    class PyroSession:
  File "D:\MyProjects\project\venv\lib\site-packages\TGConvertor\manager\sessions\pyro.py", line 70, in PyroSession
    user_id: None | int = None,
TypeError: unsupported operand type(s) for |: 'NoneType' and 'type'

**Comment by frymex** [comment]
install python 3.10 and above

**Comment by nazar220160** [comment]
Fixed, update the library
